/**
 * Generate downloadable you.json and you.md from profile data.
 * Adapted for Convex backend — uses our youJson schema.
 */

export function generateYouJson(profile: {
  username: string;
  name: string;
  youJson?: Record<string, unknown> | null;
  isClaimed: boolean;
  avatarUrl?: string | null;
}): Record<string, unknown> {
  if (profile.youJson) {
    return {
      ...profile.youJson,
      username: profile.username,
      is_claimed: profile.isClaimed,
    };
  }

  return {
    $schema: "you-md/v1",
    username: profile.username,
    identity: { name: profile.name },
    is_claimed: profile.isClaimed,
  };
}

export function generateYouMd(profile: {
  username: string;
  name: string;
  youJson?: Record<string, unknown> | null;
}): string {
  const data = profile.youJson as Record<string, any> | null;
  const lines: string[] = [];
  const name = data?.identity?.name || profile.name || profile.username;

  lines.push(`# ${name}`);
  if (data?.identity?.tagline) lines.push(`> ${data.identity.tagline}`);
  lines.push("");

  const bio = data?.identity?.bio?.long || data?.identity?.bio?.medium || data?.identity?.bio?.short;
  if (bio) {
    lines.push(bio);
    lines.push("");
  }

  if (data?.identity?.location) lines.push(`Location: ${data.identity.location}`);
  lines.push("");

  if (data?.now?.focus?.length) {
    lines.push("## Now");
    data.now.focus.forEach((item: string) => lines.push(`- ${item}`));
    lines.push("");
  }

  if (data?.projects?.length) {
    lines.push("## Projects");
    data.projects.forEach((p: any) => {
      lines.push(`- **${p.name}** ${p.role ? `(${p.role})` : ""} ${p.status ? `[${p.status}]` : ""}`);
      if (p.description) lines.push(`  ${p.description}`);
    });
    lines.push("");
  }

  if (data?.values?.length) {
    lines.push("## Values");
    data.values.forEach((v: string) => lines.push(`- ${v}`));
    lines.push("");
  }

  if (data?.links) {
    const linkEntries = Object.entries(data.links).filter(([, url]) => url);
    if (linkEntries.length > 0) {
      lines.push("## Links");
      linkEntries.forEach(([platform, url]) => lines.push(`- ${platform}: ${url}`));
      lines.push("");
    }
  }

  lines.push("---");
  lines.push(`*Generated by [you.md](https://you.md) on ${new Date().toISOString().split("T")[0]}*`);

  return lines.join("\n");
}

export function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
