export interface Profile {
  username: string;
  name: string;
  tagline: string;
  avatarUrl: string;
  verification: { verified: boolean };
  agentMetrics: { totalReads: number };
  freshness: { score: number };
  updatedAt: number;
  isClaimed?: boolean;
}

// Houston's profile is real and claimed. All others are unclaimed placeholders
// based on real public AI/SaaS founders — their context SHOULD be here.
export const sampleProfiles: Profile[] = [
  {
    username: "houstongolden",
    name: "Houston Golden",
    tagline: "Founder, You.md + BAMF Media. Building the identity context protocol.",
    avatarUrl: "/assets/houston-portrait.jpeg",
    verification: { verified: true },
    agentMetrics: { totalReads: 14200 },
    freshness: { score: 95 },
    updatedAt: Date.now() - 1000 * 60 * 12,
    isClaimed: true,
  },
  {
    username: "darioamodei",
    name: "Dario Amodei",
    tagline: "CEO, Anthropic. Building safe, beneficial AI.",
    avatarUrl: "",
    verification: { verified: false },
    agentMetrics: { totalReads: 0 },
    freshness: { score: 0 },
    updatedAt: 0,
    isClaimed: false,
  },
  {
    username: "sama",
    name: "Sam Altman",
    tagline: "CEO, OpenAI. AGI researcher and investor.",
    avatarUrl: "",
    verification: { verified: false },
    agentMetrics: { totalReads: 0 },
    freshness: { score: 0 },
    updatedAt: 0,
    isClaimed: false,
  },
  {
    username: "guillaumelaforge",
    name: "Guillaume Lample",
    tagline: "Co-founder, Mistral AI. Building open-weight foundation models.",
    avatarUrl: "",
    verification: { verified: false },
    agentMetrics: { totalReads: 0 },
    freshness: { score: 0 },
    updatedAt: 0,
    isClaimed: false,
  },
  {
    username: "swyx",
    name: "Shawn Wang",
    tagline: "Founder, smol.ai. AI engineer, writer, speaker.",
    avatarUrl: "",
    verification: { verified: false },
    agentMetrics: { totalReads: 0 },
    freshness: { score: 0 },
    updatedAt: 0,
    isClaimed: false,
  },
  {
    username: "emilkowalski",
    name: "Emil Kowalski",
    tagline: "Design engineer. Creator of Sonner, Vaul, Motion. Vercel.",
    avatarUrl: "",
    verification: { verified: false },
    agentMetrics: { totalReads: 0 },
    freshness: { score: 0 },
    updatedAt: 0,
    isClaimed: false,
  },
  {
    username: "raaborman",
    name: "Amjad Masad",
    tagline: "CEO, Replit. Making programming accessible to everyone.",
    avatarUrl: "",
    verification: { verified: false },
    agentMetrics: { totalReads: 0 },
    freshness: { score: 0 },
    updatedAt: 0,
    isClaimed: false,
  },
  {
    username: "karpathy",
    name: "Andrej Karpathy",
    tagline: "AI researcher. Ex-Tesla AI, ex-OpenAI. Educator.",
    avatarUrl: "",
    verification: { verified: false },
    agentMetrics: { totalReads: 0 },
    freshness: { score: 0 },
    updatedAt: 0,
    isClaimed: false,
  },
  {
    username: "shl",
    name: "Sahil Lavingia",
    tagline: "Founder, Gumroad. Investor. Writer.",
    avatarUrl: "",
    verification: { verified: false },
    agentMetrics: { totalReads: 0 },
    freshness: { score: 0 },
    updatedAt: 0,
    isClaimed: false,
  },
  {
    username: "disler",
    name: "Peter Disler",
    tagline: "Creator of The Library. AI-native development tools.",
    avatarUrl: "",
    verification: { verified: false },
    agentMetrics: { totalReads: 0 },
    freshness: { score: 0 },
    updatedAt: 0,
    isClaimed: false,
  },
  {
    username: "levelsio",
    name: "Pieter Levels",
    tagline: "Indie maker. nomadlist, remoteok, photoai. Ships fast.",
    avatarUrl: "",
    verification: { verified: false },
    agentMetrics: { totalReads: 0 },
    freshness: { score: 0 },
    updatedAt: 0,
    isClaimed: false,
  },
  {
    username: "alexalbert",
    name: "Alex Albert",
    tagline: "Head of Claude Relations, Anthropic.",
    avatarUrl: "",
    verification: { verified: false },
    agentMetrics: { totalReads: 0 },
    freshness: { score: 0 },
    updatedAt: 0,
    isClaimed: false,
  },
];
