/**
 * Host-link engine — the ONE implementation that links You.md skills and
 * YouStack adapters into agent hosts (Claude Code, Codex, Cursor, fallback).
 *
 * P11 / PRODUCT-AUDIT #13 / FEATURE-ROADMAP 3.7: there used to be multiple
 * drifting per-host link code paths (youstack.ts switch + skills.ts switch).
 * They are consolidated here. Hosts differ ONLY by adapter config (target
 * dir, file naming, frontmatter shape) — never by separate code paths.
 *
 * Claude Code discovery contract (the empirical release gate):
 *   - every linked skill lands at `.claude/skills/<skill-name>/SKILL.md`
 *   - SKILL.md frontmatter parses and has non-empty `name` + `description`
 *   - frontmatter `name` matches the skill directory name
 *   - the skill body is non-empty
 */

import * as fs from "fs";
import * as path from "path";
import matter from "gray-matter";

// ─── Types ────────────────────────────────────────────────────────────

export type HostLinkLayout = "skill-dir" | "flat-file" | "concat-file";

export interface HostAdapterConfig {
  /** Normalized host id (claude-code, codex, cursor, or a fallback id). */
  host: string;
  /**
   * skill-dir   → <root>/<name>/SKILL.md (Claude Code / Codex discovery layout)
   * flat-file   → <root>/<prefix><name>.md
   * concat-file → single <root>/<concatFileName> with one section per skill
   */
  layout: HostLinkLayout;
  /** Path segments of the host's link root, relative to the target dir. */
  rootSegments: string[];
  /** flat-file only: filename prefix (e.g. "youstacks-"). */
  filePrefix?: string;
  /** concat-file only: output filename (e.g. "youmd.md"). */
  concatFileName?: string;
  /** concat-file only: header parts joined with "\n" before sections. */
  concatHeaderParts?: string[];
  /**
   * ensure → guarantee parseable frontmatter with name (matching the skill
   *          dir) + description. none → emit content untouched.
   */
  frontmatter: "ensure" | "none";
}

/** One linkable skill: name + rendered markdown (may include frontmatter). */
export interface HostSkillUnit {
  name: string;
  description?: string;
  content: string;
}

export interface HostLinkPlanEntry {
  host: string;
  relativePath: string;
  content: string;
}

export interface HostLinkWriteResult extends HostLinkPlanEntry {
  targetPath: string;
  wrote: boolean;
}

export interface SkillDiscoveryCheck {
  /** Path of the checked SKILL.md (relative or absolute, as provided). */
  path: string;
  /** Frontmatter name, when parseable. */
  name: string;
  ok: boolean;
  problems: string[];
}

export interface SkillDiscoveryReport {
  ok: boolean;
  checks: SkillDiscoveryCheck[];
}

// ─── Built-in adapter configs ─────────────────────────────────────────

/** Adapter configs for YouStack manifest links (`youmd stack link`). */
export function youStackHostAdapterConfig(host: string): HostAdapterConfig {
  switch (host) {
    case "claude-code":
      // P11 fix: Claude Code only discovers `.claude/skills/<name>/SKILL.md`.
      // The legacy `.claude/skills/youstacks/<slug>/SKILL.md` nesting was
      // never picked up by the host.
      return {
        host,
        layout: "skill-dir",
        rootSegments: [".claude", "skills"],
        frontmatter: "ensure",
      };
    case "codex":
      return {
        host,
        layout: "skill-dir",
        rootSegments: [".codex", "skills", "youstacks"],
        frontmatter: "ensure",
      };
    case "cursor":
      return {
        host,
        layout: "flat-file",
        rootSegments: [".cursor", "rules"],
        filePrefix: "youstacks-",
        frontmatter: "none",
      };
    default:
      return {
        host,
        layout: "flat-file",
        rootSegments: [".you", "adapters", host],
        frontmatter: "none",
      };
  }
}

export type InstalledSkillsTarget = "claude" | "cursor" | "codex";

/** Adapter configs for installed-skill links (`youmd skill link`). */
export function installedSkillsHostAdapterConfig(
  target: InstalledSkillsTarget
): HostAdapterConfig {
  switch (target) {
    case "claude":
      // P11 fix: was `.claude/skills/youmd/<name>.md` — flat .md files that
      // Claude Code never discovers. Now `.claude/skills/<name>/SKILL.md`.
      return {
        host: "claude-code",
        layout: "skill-dir",
        rootSegments: [".claude", "skills"],
        frontmatter: "ensure",
      };
    case "codex":
      return {
        host: "codex",
        layout: "flat-file",
        rootSegments: [".codex", "skills", "youmd"],
        frontmatter: "none",
      };
    case "cursor":
      return {
        host: "cursor",
        layout: "concat-file",
        rootSegments: [".cursor", "rules"],
        concatFileName: "youmd.md",
        concatHeaderParts: [
          "# You.md Identity Skills\n",
          "> Auto-generated by youmd skill link. Do not edit manually.\n",
        ],
        frontmatter: "none",
      };
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────

export function isSafeHostRelativePath(value: string): boolean {
  if (!value || path.isAbsolute(value) || value.startsWith("~")) return false;
  const parts = value.split(/[\\/]+/);
  return !parts.includes("..");
}

function isSafeUnitName(name: string): boolean {
  return isSafeHostRelativePath(name) && !name.includes("/") && !name.includes("\\");
}

function parseFrontmatter(content: string): { data: Record<string, unknown>; body: string } | null {
  try {
    const parsed = matter(content);
    return { data: parsed.data as Record<string, unknown>, body: parsed.content };
  } catch {
    return null;
  }
}

function hasFrontmatterBlock(content: string): boolean {
  return /^---\r?\n/.test(content);
}

/**
 * Guarantee that skill content carries parseable frontmatter with a `name`
 * matching the skill's directory and a non-empty `description` — the
 * conditions Claude Code requires for discovery.
 *
 * Content that already satisfies the contract passes through byte-identical.
 */
export function ensureSkillFrontmatter(
  content: string,
  name: string,
  fallbackDescription?: string
): string {
  const parsed = parseFrontmatter(content);
  if (parsed && hasFrontmatterBlock(content)) {
    const fmName = typeof parsed.data.name === "string" ? parsed.data.name.trim() : "";
    const fmDescription =
      typeof parsed.data.description === "string" ? parsed.data.description.trim() : "";
    if (fmName === name && fmDescription && parsed.body.trim().length > 0) {
      return content;
    }
  }

  const body = parsed ? parsed.body : content;
  const data: Record<string, unknown> = parsed ? { ...parsed.data } : {};
  const description =
    typeof data.description === "string" && data.description.trim().length > 0
      ? (data.description as string)
      : fallbackDescription || `${name} (linked by You.md)`;

  const extraKeys = Object.keys(data).filter((key) => key !== "name" && key !== "description");
  if (extraKeys.length === 0) {
    // Deterministic minimal emission — byte-compatible with the legacy
    // stack-adapter frontmatter shape.
    return `---\nname: ${name}\ndescription: ${description}\n---\n\n${body.replace(/^\r?\n/, "")}`;
  }
  return matter.stringify(body.replace(/^\r?\n/, ""), { ...data, name, description });
}

function renderUnitContent(unit: HostSkillUnit, config: HostAdapterConfig): string {
  if (config.frontmatter === "ensure") {
    return ensureSkillFrontmatter(unit.content, unit.name, unit.description);
  }
  return unit.content;
}

/** Default relative path the engine emits for one skill on a host. */
export function hostLinkRelativePath(config: HostAdapterConfig, name: string): string {
  if (config.layout === "skill-dir") {
    return path.join(...config.rootSegments, name, "SKILL.md");
  }
  if (config.layout === "concat-file") {
    return path.join(...config.rootSegments, config.concatFileName || "youmd.md");
  }
  return path.join(...config.rootSegments, `${config.filePrefix || ""}${name}.md`);
}

// ─── Plan + write ─────────────────────────────────────────────────────

/**
 * Build the per-host link plan: paths + rendered content.
 *
 * `explicitRelativePaths` lets a manifest declare adapter output paths that
 * override the host's default layout (existing youstack.json behavior).
 */
export function buildHostLinkPlan(
  units: HostSkillUnit[],
  config: HostAdapterConfig,
  options: { explicitRelativePaths?: string[] } = {}
): HostLinkPlanEntry[] {
  for (const unit of units) {
    if (!isSafeUnitName(unit.name)) {
      throw new Error(`Unsafe skill name for ${config.host}: ${unit.name}`);
    }
  }

  let entries: HostLinkPlanEntry[];

  if (options.explicitRelativePaths && options.explicitRelativePaths.length > 0) {
    // Declared adapter paths share the host-rendered content of the unit.
    const content = units.length > 0 ? renderUnitContent(units[0], config) : "";
    entries = options.explicitRelativePaths.map((relativePath) => ({
      host: config.host,
      relativePath,
      content,
    }));
  } else if (config.layout === "concat-file") {
    const parts: string[] = [...(config.concatHeaderParts || [])];
    for (const unit of units) {
      parts.push(`\n---\n\n## ${unit.name}\n\n${renderUnitContent(unit, config)}`);
    }
    entries = [
      {
        host: config.host,
        relativePath: hostLinkRelativePath(config, ""),
        content: parts.join("\n"),
      },
    ];
  } else {
    entries = units.map((unit) => ({
      host: config.host,
      relativePath: hostLinkRelativePath(config, unit.name),
      content: renderUnitContent(unit, config),
    }));
  }

  for (const entry of entries) {
    if (!isSafeHostRelativePath(entry.relativePath)) {
      throw new Error(`Unsafe adapter path for ${config.host}: ${entry.relativePath}`);
    }
  }

  return entries;
}

/** Write a link plan under `targetDir` (or preview it with dryRun). */
export function writeHostLinkPlan(
  plan: HostLinkPlanEntry[],
  targetDir: string,
  options: { dryRun?: boolean } = {}
): HostLinkWriteResult[] {
  const resolvedTarget = path.resolve(targetDir);
  return plan.map((entry) => {
    const targetPath = path.join(resolvedTarget, entry.relativePath);
    if (!options.dryRun) {
      fs.mkdirSync(path.dirname(targetPath), { recursive: true });
      fs.writeFileSync(targetPath, entry.content);
    }
    return { ...entry, targetPath, wrote: !options.dryRun };
  });
}

// ─── Empirical discovery release gate ─────────────────────────────────

/**
 * Verify one emitted SKILL.md against the Claude Code discovery contract:
 * parseable frontmatter, non-empty name + description, name matching the
 * parent directory, non-empty body.
 */
export function verifySkillDiscoveryEntry(filePath: string, content: string): SkillDiscoveryCheck {
  const problems: string[] = [];
  let data: Record<string, unknown> = {};
  let body = "";

  try {
    const parsed = matter(content);
    data = parsed.data as Record<string, unknown>;
    body = parsed.content;
  } catch (error) {
    const message = error instanceof Error ? error.message.split("\n")[0] : String(error);
    problems.push(`frontmatter does not parse: ${message}`);
  }

  let fmName = "";
  if (problems.length === 0) {
    if (!hasFrontmatterBlock(content)) {
      problems.push("missing frontmatter block (--- ... ---)");
    }
    fmName = typeof data.name === "string" ? data.name.trim() : "";
    const fmDescription = typeof data.description === "string" ? data.description.trim() : "";
    if (!fmName) problems.push("frontmatter is missing name");
    if (!fmDescription) problems.push("frontmatter is missing description");

    const dirName = path.basename(path.dirname(filePath));
    if (fmName && path.basename(filePath) === "SKILL.md" && fmName !== dirName) {
      problems.push(`frontmatter name "${fmName}" does not match its directory "${dirName}"`);
    }
    if (body.trim().length === 0) problems.push("skill body is empty");
  }

  return { path: filePath, name: fmName, ok: problems.length === 0, problems };
}

/**
 * Verify every SKILL.md in a set of emitted link entries (plan entries or
 * write results). Non-SKILL.md outputs (cursor rules, fallback adapters)
 * are not discovery surfaces and are skipped.
 */
export function verifySkillDiscovery(
  entries: Array<{ relativePath?: string; targetPath?: string; content: string }>
): SkillDiscoveryReport {
  const checks = entries
    .map((entry) => ({ filePath: entry.targetPath || entry.relativePath || "", content: entry.content }))
    .filter((entry) => path.basename(entry.filePath) === "SKILL.md")
    .map((entry) => verifySkillDiscoveryEntry(entry.filePath, entry.content));
  return { ok: checks.every((check) => check.ok), checks };
}

/**
 * CI helper: verify every `<skillsRoot>/<name>/SKILL.md` on disk (e.g.
 * `.claude/skills/`) against the discovery contract.
 */
export function verifySkillFilesOnDisk(skillsRoot: string): SkillDiscoveryReport {
  const checks: SkillDiscoveryCheck[] = [];
  if (fs.existsSync(skillsRoot) && fs.statSync(skillsRoot).isDirectory()) {
    for (const entry of fs.readdirSync(skillsRoot, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const skillPath = path.join(skillsRoot, entry.name, "SKILL.md");
      if (!fs.existsSync(skillPath)) continue;
      checks.push(verifySkillDiscoveryEntry(skillPath, fs.readFileSync(skillPath, "utf-8")));
    }
  }
  return { ok: checks.every((check) => check.ok), checks };
}

/**
 * Detection helper: have any of the given skills been linked into the
 * Claude Code discovery layout under `root`? Also recognizes the legacy
 * `.claude/skills/youmd/` directory so older links still count.
 */
export function hasLinkedClaudeSkills(root: string, skillNames: string[]): boolean {
  const skillsRoot = path.join(root, ".claude", "skills");
  for (const name of skillNames) {
    if (fs.existsSync(path.join(skillsRoot, name, "SKILL.md"))) return true;
  }
  return fs.existsSync(path.join(skillsRoot, "youmd"));
}
