import * as fs from "fs";
import * as path from "path";
import { describe, expect, it } from "vitest";

const repoRoot = path.resolve(__dirname, "..", "..", "..");
const webHookPath = path.join(repoRoot, "src", "hooks", "useYouAgent.ts");

describe("web /new computer bootstrap prompt parity", () => {
  it("keeps the shell prompt aligned with the strict machine setup gate", () => {
    const source = fs.readFileSync(webHookPath, "utf-8");

    expect(source).toContain("read:private");
    expect(source).toContain("write:bundle");
    expect(source).toContain("write:memories");
    expect(source).toContain('"vault"');
    expect(source).toContain("ACTIVE + Top Priority/Focusing");
    expect(source).toContain("clone only projects marked ACTIVE plus Top Priority/Focusing");
    expect(source).toContain("inactive, unsorted, on-ice, abandoned, killed, and unreviewed GitHub-only repos are skipped by default");
    expect(source).toContain("YOU_CODE_ROOT");
    expect(source).toContain("YOUMD_CODE_ROOT");
    expect(source).toContain("YOU_REQUIRE_ENV_VAULT=1");
    expect(source).toContain("checking local prerequisites: Homebrew, Node 22/npm, git, gh, bun, pnpm");
    expect(source).toContain("YOU_INSTALL_CHANNEL=source YOU_SOURCE_REF=main bash");
    expect(source).toContain('MIN_YOUMD_VERSION="\\${YOU_MIN_VERSION:-\\${YOUMD_MIN_VERSION:-0.8.12}}"');
    expect(source).toContain("ensure_youmd_min_version");
    expect(source).toContain("you \\${MIN_YOUMD_VERSION}+ is required for Secret Vault, agent bus, agent stack inventory, and fresh-machine restore");
    expect(source).toContain("proving canonical ~/.you home migration");
    expect(source).toContain("you machine migrate-home --yes || true");
    expect(source).toContain("run_agent_stack_inventory()");
    expect(source).toContain('INVENTORY_DIR="\\${YOU_AGENT_STACK_INVENTORY_DIR:-\\${YOUMD_AGENT_STACK_INVENTORY_DIR:-$HOME/.you/agent-stack-inventory}}"');
    expect(source).toContain('you skill inventory --out-dir "$INVENTORY_DIR" --register-catalog --sync');
    expect(source).toContain("require GitHub CLI auth before private shared-skill/project repos clone");
    expect(source).toContain("Behind-the-scenes operating rule");
    expect(source).toContain("use the You.md CLI and You Agent yourself before asking Houston");
    expect(source).toContain("use the installed You.md CLI behind the scenes for status, skill sync, Secret Vault pull, portfolio graph hydration, machine verification, and You Agent context routing");
    expect(source).toContain("gh auth login -h github.com -p https -s repo");
    expect(source).toContain("checking You.md Secret Vault for the latest encrypted env vault");
    expect(source).toContain("you env vault device-register");
    expect(source).toContain("checking You.md Secret Vault for the latest encrypted env vault and trusted-device envelope");
    expect(source).toContain('you env vault pull --out "$SECRET_VAULT_DIR" --restore --root "$ROOT" --map-existing --existing-only --skip-agent-auth');
    expect(source).toContain("restored env vault through trusted-device Secret Vault");
    expect(source).toContain("source Mac action: you env vault share");
    expect(source).toContain("registered Secret Vault device and is waiting for source Mac trusted-device share");
    expect(source).toContain("you env vault push --root ~/Desktop/CODE_2025 --out ~/Desktop/youmd-env-vault");
    expect(source).toContain("you env vault share");
    expect(source).toContain("you env backup --root ~/Desktop/CODE_2025 --out ~/Desktop/youmd-env-vault");
    expect(source).toContain("YOU_ENV_VAULT=/path/to/env-vault-*.tar.enc");
    expect(source).toContain("YOU_ALLOW_LOCAL_ENV_VAULT_FALLBACK=1");
    expect(source).toContain("local/iCloud passphrase vault fallback disabled by default");
    expect(source).toContain("This strict fresh-machine flow intentionally does not ask for a local vault passphrase on the new Mac by default");
    expect(source).toContain('for DEFAULT_ENV_VAULT_DIR in "$HOME/Desktop/youmd-env-vault"');
    expect(source).toContain("com~apple~CloudDocs/Desktop/youmd-env-vault");
    expect(source).toContain('export YOU_ENV_VAULT="$ENV_VAULT_PATH"');
    expect(source).toContain("Local/iCloud passphrase fallback runs only when `YOU_ALLOW_LOCAL_ENV_VAULT_FALLBACK=1`");
    expect(source).toContain("reconciling identity/skills after env-vault and source-Mac updates");
    expect(source).toContain("reconcile `you pull && you sync` after env-vault handling");
    expect(source).toContain("fresh machine \\$(hostname) reconciled You.md bundle after env-vault handling");
    expect(source).toContain("--map-existing --existing-only --skip-agent-auth");
    expect(source).toContain("YOU_ENV_VAULT_KEYCHAIN_SERVICE:-\\${YOUMD_ENV_VAULT_KEYCHAIN_SERVICE:-you-env-vault}");
    expect(source).toContain("security find-generic-password");
    expect(source).toContain("trusted-device key envelope");
    expect(source).toContain("per-device encrypted passphrase envelopes");
    expect(source).toContain("YOU_PORTFOLIO_HYDRATE_TIMEOUT_SECONDS");
    expect(source).toContain("YOUMD_PORTFOLIO_HYDRATE_TIMEOUT_SECONDS");
    expect(source).toContain("YOU_EXPAND_TO_90_DAYS");
    expect(source).toContain("YOUMD_EXPAND_TO_90_DAYS");
    expect(source).toContain('PATH="$HOME/.you/bin:$HOME/.you/npm-global/bin:$HOME/.youmd/bin:$HOME/.youmd/npm-global/bin');
    expect(source).toContain('shellHomeAssignment("YOU_CODE_ROOT", FRESH_MACHINE_BOOTSTRAP_ROOT)');
    expect(source).toContain('you machine sync-now --root "$ROOT" --max-projects "$LIMIT"');
    expect(source).toContain("where the agent stack inventory JSON/HTML was written");
  });
});
